### ISSUE TITLE
Code is not pulling correct numbers on entry

### ISSUE THREAD

**Issue by delize** [wolfascu/GoogleApps_SumByColor#3]
After coming across your code on stackoverflow, it looks like this is exactly what I need. I was pretty excited to try it out as it would help me simplify my spreadsheet

So I set it up, used the "getBackgroundColor" function with "" around the cell number, and it pulls the color code (in this case #ff0000 or #b7b7b7). However, when I use the "sumWhereBackgroundColorIs("#ff0000","B3:B500", "", "B3:B500")" it responds with 0 cells holding that color, even though I have in B3 that is being used by getBackgroundColor to let me know at hex code to check for.

I really do think this would do exactly what I am hoping for. I tried using the Google Scripts debugger, but it isn't incredibly helpful in this situation (as it expects there to be a range of something, and there isn't one).

**Comment by wolfascu** [comment]
@delize Try removing the quotes around the last parameter:

    =sumWhereBackgroundColorIs("#ff0000","B3:B500", "", B3:B500)

If it still doesn't work, perhaps you can share the document so I can take a look.

**Comment by delize** [comment]
I get the following results (same issue, except now it displays #NUM) with the above string.

I unfortunately can't share this specific spreadsheet, but I can try to share a different spreadsheet where I get the same result. I have displayed pictures of the initial spreadsheet below:
![2015-10-02_04-36-53](https://cloud.githubusercontent.com/assets/4028612/10243601/79253af4-68bf-11e5-9bed-a6b2c34aafce.png)
![2015-10-02_04-37-10](https://cloud.githubusercontent.com/assets/4028612/10243602/79269494-68bf-11e5-8048-0fda0917b019.png)
![2015-10-02_04-35-21](https://cloud.githubusercontent.com/assets/4028612/10243604/79293f28-68bf-11e5-948f-9feb7a7e10c2.png)
![2015-10-02_04-35-55](https://cloud.githubusercontent.com/assets/4028612/10243603/7928456e-68bf-11e5-97e8-33a8b9263e74.png)

Here is a spreadsheet where I receive the same issue.
https://docs.google.com/spreadsheets/d/1suirxEiZH9o7bkN1Pd9sVM5v0P-00vapVv6RrIoeUhQ/edit?usp=sharing

**Comment by wolfascu** [comment]
For me, the doc you shared seems to work fine:

![image](https://cloud.githubusercontent.com/assets/845200/10244357/454d1bf0-6907-11e5-8ad9-4f61d4ce8579.png)

**Comment by delize** [comment]
Unless I am mistaken, shouldn't the count be two? As the background color in cells B4 and C4 do not meet #ff0000 requirement?

**Comment by wolfascu** [comment]
It's not a count; it's a sum. And if the sum encounters cells with non-numeric values it assumes them to be 0.

**Comment by delize** [comment]
Yeah, I just realized that after re-reading the description again. Im mistaken. Thanks for your instant response time though. My bad.

**Comment by wolfascu** [comment]
Awesome! Glad this is solved.
